apiVersion: v1
kind: Secret
metadata:
  name: API_KEY
  namespace: default
type: Opaque
data:
  service_account_key: eyBoZWxsbzogInNkZmFzZCIsCnBhc3N3b3JkOiAid2hhdCIgfQo=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: nginx
    spec:
      automountServiceAccountToken: true
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
            volumeMounts:
            - name: API_KEY
              mountPath: /root/key.json
              subPath: key.json
            env:
            - name: "API_KEY"
              valueFrom:
                secretKeyRef:
                  name: API_KEY
                  key: token
      serviceAccount: svc
      serviceAccountName: svc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
      port: 80
      targetPort: 80